permalink: /:year/:month/:day/:title.html
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      entity: Nimble Solution Architects
      site_author: Nimble SA
      site_description: Nimble Solution Architects
      title: Nimble Solution Architects
      subtitle: Data Driven Story Telling
      quip: Cloud Native Data Publishing
      logo_url: /www/img/branding/logo.png
      style_css: /www/css/www.css
      site_js: /www/js/dashboard.js
      branding_ico: /www/img/branding/brand.ico
      g_analytics_id: G-2Q394P0Z4Y