permalink: /:year/:month/:day/:title.html
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      entity: Kingfisher by Nimble SA
      site_author: Kingfisher
      site_description: Kingfisher by Nimble SA
      title: Kingfisher by Nimble SA
      subtitle: Data Driven Decision Advantage
      quip: Cloud Native Data Publishing
      logo_url: /www/img/branding/logo.png
      style_css: /www/css/www.css
      site_js: /www/js/dashboard.js
      branding_ico: /www/img/branding/brand.ico
      g_analytics_id: G-2Q394P0Z4Y